<div class="showrooms">
<div class = "page-title category-title">
	<h1><?php echo $this->__("Friends' showrooms"); ?></h1>
</div>
<?php $isLogin = Mage::getSingleton('showroom/session')->isLoggedIn();?>
<?php //if($isLogin){?>
    <?php $user = Mage::helper('showroom/facebook')->getFbUser()?>
    <!--div id="bt-loginfb">
            <a class="fb_button fb_button_medium" onclick="login();return false;" href="#">
                <span class="fb_button_text"><?php echo $this->__('Re connect to facebook') ?></span>
            </a>
    </div-->
    <script src="http://connect.facebook.net/en_US/all.js"></script>
	<script type="text/javascript">
		<?php //if (!$user) { ?>
		var newwindow;
		var intId;
		function login(){
			var  screenX    = typeof window.screenX != 'undefined' ? window.screenX : window.screenLeft;
			var	 screenY    = typeof window.screenY != 'undefined' ? window.screenY : window.screenTop;
			var	 outerWidth = typeof window.outerWidth != 'undefined' ? window.outerWidth : document.body.clientWidth;
			var	 outerHeight = typeof window.outerHeight != 'undefined' ? window.outerHeight : (document.body.clientHeight - 22);
			var	 width    = 500;
			var	 height   = 270;
			var	 left     = parseInt(screenX + ((outerWidth - width) / 2), 10);
			var	 top      = parseInt(screenY + ((outerHeight - height) / 2.5), 10);
			var	 features = (
					'width=' + width +
					',height=' + height +
					',left=' + left +
					',top=' + top
				  );
		
			newwindow=window.open('<?php echo $this->getFbLoginButtonUrl() ?>','Connect to facebook',features);
		
			if (window.focus) {
				newwindow.focus()
			}
			return false;
		}
		<?php //} ?>
    </script>
<?php //}?>
<?php
	$session = Mage::getSingleton('showroom/session');
	$profile = Mage::helper('showroom')->getProfileByCustomerId($session->getCustomer()->getId());
	$friends = $this->getFriendShowroom();
	$block = $this->getLayout()->createBlock('showroom/friendlist');
	$block->setShowrooms($friends);
	echo $block->toHtml();
?>
</div>