<?php 
    $stylist=$this->getStylist();
    if(count($stylist)){
?>
<div class="showrooms-left">
<div class="block <?php if (count($stylist)>4) echo 'block-friends';?>">
    <div class="block-title">
        <strong><span><?php echo $this->__('Stylist'); ?></span></strong>
    </div>
    <div class="block-content">
    <ul>      
      
      <?php foreach($stylist as $showroom): ?>
        <?php $profile = Mage::getModel('showroom/showroomprofile')->load($showroom->getProfileId());?>
        <?php 
          $imageresize=Mage::helper('showroom/image')->init($profile,'showroom'.DS.'profile'.DS.$profile->getId())->resize(50);
        ?>
        <li>
          <a href="<?php echo $this->getUrl('showroom/index/overview',array('id'=>$showroom->getId()));?>">
            <div class="showroom-avatar-menu">
              <img src="<?php echo $imageresize ?>"/>
              </div>
            <h5><?php echo $profile->getName(); ?></h5>
          </a>
        </li>
      <?php endforeach; ?>
      
    </ul>
  </div>
</div>
</div>
<?php } ?>