<html xmlns:fb="http://ogp.me/ns/fb#">
<?php 
    $profile=$this->getProfile();
    $showroom=$this->getShowroom();
    $showroomlogin=Mage::helper('showroom')->getShowroomLogin();
    $labelMenu=$this->__('My Show Room');
    $id  = $this->getRequest()->getParam('id');
    if($id){
        $showroom=Mage::getModel('showroom/showroom')->load($id);
        $profile=$this->getProfileByShowroom($showroom);
        $labelMenu=$profile->getName().' \' showroom';
        $profile_temp=$this->getProfile();
        if($profile==$profile_temp)
            $labelMenu=$this->__('My Show Room');
    }
    if($showroom->getShowroomId()){
?>
<div id="image_avatar_menu">
    <?php 
        $imageresize=Mage::helper('showroom/image')->init($profile,'showroom'.DS.'profile'.DS.$profile->getId())->resize(200);
    ?>
    <img style="width: 100%" src="<?php echo $imageresize; ?>" />
</div>
<div class="showroom-detail">
    <div class="showroom-name"><?php echo $this->__('Name: ').$profile->getName();?></span></div>
   <div class="follows"> <span><?php echo $this->__('Follows: ') ?></span> <div class="number-follows" id="follows_<?php echo $showroom->getId() ?>"><?php echo $showroom->getFollowNumber() ?></div></div>
</div>
<?php if($showroomlogin->getShowroomId()==$id||!$id){ ?>
<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo $labelMenu; ?></span></strong>
    </div>
    <div class="block-content">
        <ul>
            <?php $_links = $this->getShowRoomLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>
            <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($_link->getUrl()==$this->helper('core/url')->getCurrentUrl()): ?>
                    <li class="current<?php echo ($_last ? ' last' : '') ?>"><strong><?php echo $_link->getLabel() ?></strong></li>
                <?php else: ?>
                    <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php }} ?>