<?php
    ob_start();
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
    $_facebookId = preg_replace('/[\D]/', '', $this->getLayout()->createBlock('cms/block')->setBlockId('facebook-app-id ')->toHtml());
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<div class="popup">
    <div class="qcenter">
        <div class="heading">
            <strong class="title"><?php echo $this->__('Quickview') ?></strong>
            <a class="close" href="#"><?php echo $this->__('Close') ?></a>
        </div>
        
        <div class="holder popup-content">
            <div class="gallery-holder2">
                <?php echo $this->getChildHtml('media') ?>
				<div class="clear"></div>
                <?php echo $this->getChildHtml('related_products') ?>
            </div>
            
            <div class="tabs-column">
                <div class="tabset">
                    <ul class="tabset-list">
                        <li><a class="active" href="#" rel="tab-overview"><?php echo $this->__('Overview') ?></a></li>
                        <?php if ($_product->getDescription()): ?>
                        <li><a href="#" rel="tab-description"><?php echo $this->__('Description') ?></a></li>
                        <?php endif ?>
                    </ul>
                </div>
                <div class="tab-block">
                    <div>
                        <a href="<?php echo $_product->getProductUrl() ?>"><strong class="heading2"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></strong></a>
                        <div class="heading-holder">
                            <?php echo $this->getPriceHtml($_product) ?>
                            <?php echo $this->getTierPriceHtml() ?>
                            <span class="onsale"><?php echo $this->__('on sale!') ?></span>
                        </div>
                        <div class="holder">
                            <?php echo $this->getChildHtml('alert_urls') ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
                        </div>
                        
                        <div id="tab-overview">
                            <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" class="addcart-form" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                                <fieldset>
                                    <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                                    <input type="hidden" name="related_product" id="related-products-field" value="" />
                                    <?php if (!$this->hasOptions()): ?>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php echo $this->getChildHtml('availability') ?><?php echo $this->getChildHtml('product_type_data') ?>
                                            <?php echo $this->getChildHtml('addtocart') ?>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php echo $this->getChildHtml('bundleprices') ?>
                                        <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                                            <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                                            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                                        <?php endif ?>
                                    <?php endif ?>
                                </fieldset>
                            </form>
                            
                            <?php if ($_facebookId): ?>
                            <div class="holder">
                            	<div class="facebook-line">
                			    <div id="fb-root"></div>
                                <script type="text/javascript">
                                //<![CDATA[
                                    window.fbAsyncInit = function() {
                                        FB.init({
                                            appId  : <?php echo $_facebookId ?>,
                                            status : true,
                                            cookie : true,
                                            xfbml  : true
                                        });
                                    };
                                
                                    (function() {
                                        var e = document.createElement('script');
                                        e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
                                        e.async = true;
                                        document.getElementById('fb-root').appendChild(e);
                                    }());
                                //]]>
                                </script>
                                <div><fb:like expr:href="<?php echo Mage::helper('core/url')->getCurrentUrl() ?>" layout="box_count" /></div>
                                </div>
                            </div>
                            <?php endif ?>
                        </div>
                        
                        <?php if ($_product->getDescription()): ?>
                        <div id="tab-description" class="text-area" style="display: none">
                            <?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?>
                        </div>
                        <?php endif ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;

            if (url) {
               form.action = url;
            }
            var e = null;
            try {
           		var ajaxForm = $('product_addtocart_form');
        		ajaxForm.action += '?layovercart=true';
        		jQuery.fancybox.showActivity();
                ajaxForm.request({
                    onComplete: function(response) {
                        if (response.responseText.indexOf('<!DOCTYPE') != -1) {
                        	jQuery('#product_addtocart_form').trigger('submit');
                        } else {
                        	jQuery.fancybox.hideActivity();
                        	jQuery('div.popup').remove();
                        	jQuery('#header ul.menu > li:last').replaceWith(jQuery(response.responseText));
                        	initCartDrop();
                        	jQuery('#header ul.menu > li:last a.my-cart').trigger('mouseenter');
                        }
                    }
                });
            } catch (e) {
            }
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }

            if (button && button != 'undefined') {
                button.disabled = true;
            }

            return false;
        }
    }.bind(productAddToCartForm);

    productAddToCartForm.submitLight = function(button, url){
        if(this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
            if (this.validator.validate()) {
                if (url) {
                    this.form.action = url;
                }
                this.form.submit();
            }
            Object.extend(Validation.methods, nv);
        }
    }.bind(productAddToCartForm);
//]]>
</script>

<?php
$response = ob_get_contents(); ob_end_clean();
$response = str_replace('//<![CDATA[', '', $response);
$response = str_replace('//]]>', '', $response);

$content = preg_replace('/(<script(.*?)>(.*?)<\/script>)/ism', '', $response);
$scripts = array();
if (preg_match_all('/(<script(.*?)>(.*?)<\/script>)/ism', $response, $matches) && !empty($matches[3]))
{
    $scripts = $matches[3];
}

if ($_facebookId):
    $facebookMeta = '<meta property="fb:app_id" content="' . $_facebookId . '" />'
    	. '<meta property="og:title" content="' . $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name')  . '" />'
    	. '<meta property="og:url" content="' . $this->helper('core/url')->getCurrentUrl() . '" />'
    	. '<meta property="og:type" content="product" />'
    	. '<meta property="og:image" content="' . $this->helper('catalog/image')->init($_product, 'image') . '" />';
else:
    $facebookMeta = '';
endif;

echo json_encode(array('content' => $content, 'scripts' => $scripts, 'facebookMeta' => $facebookMeta));