<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://opengraph.org/schema/" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div id="wrapper" class="wrapper">
	<div class="page">
		<?php echo $this->getChildHtml('header') ?>
		<div class="main-container homepage">
			<div class="main" id="main">
				<?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>
				<div class="holder">
                    <?php echo $this->getChildHtml('home_region') ?>
				</div>
			</div>
			<div class="footer-container">
				<div class="footer" id="footer">
					<div class="f-columns">
						<?php echo $this->getChildHtml('footer') ?>
                        <?php echo $this->getChildHtml('before_body_end') ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>